#!/usr/bin/env python3

import polars as pd
import argparse
from pathlib import Path

def getCommandLineArguments():
    parser = argparse.ArgumentParser(description="""This python script reads the list of allocations generated by mosalloc,
along with the pebs analysis generated by mosmodel, and creates a ranked list of allocations based on how many TLB misses occured in each one
assuming they do not overlap""")
    parser.add_argument('-a', '--allocation_data', type=Path, required=True,
            help='the path to the log file containing a list of allocations and their stack-trace')
    parser.add_argument('-p', '--pebs_data', type=Path, required=True,
            help='the CSV generated from pebs using mosmodel, for the number of TLB misses per 2MB region')
    parser.add_argument('-o', '--output_file', type=Path, required=True, help='the path to the file where the output will be written')
    args = parser.parse_args()
    return args

if __name__ == "__main__":
    args = getCommandLineArguments()

    print(f"reading '{args.allocation_data}' and '{args.pebs_data}' and writing in '{args.output_file}'")
